/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnistudy_MainActivity */

#ifndef _Included_com_example_jnistudy_MainActivity
#define _Included_com_example_jnistudy_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnistudy_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnistudy_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jnistudy_MainActivity
 * Method:    formatName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnistudy_MainActivity_formatName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_jnistudy_MainActivity
 * Method:    getValidToken
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnistudy_MainActivity_getValidToken
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
